"""
A Rust block's source: its block function, its test functions and the generated main.

The generated crate's main.rs is the block's code unchanged, followed by a main that
calls the block function. Line numbers in compiler messages match the block's file.
"""
import re
from dataclasses import dataclass
from typing import List, Optional

from mage_ai.data_preparation.models.constants import BlockType

FUNCTION_NAMES = {
    BlockType.DATA_LOADER: 'load_data',
    BlockType.TRANSFORMER: 'transform',
    BlockType.DATA_EXPORTER: 'export_data',
    BlockType.CUSTOM: 'custom',
    BlockType.CONDITIONAL: 'condition',
}

_COMMENTS = re.compile(r'//[^\n]*|/\*.*?\*/', re.S)
# Strings could hold text like `fn transform(`; their content is blanked, lines kept.
_STRINGS = re.compile(r'r(#*)".*?"\1|"(?:\\.|[^"\\])*"', re.S)
_FUNCTION = re.compile(r'^[ \t]*(?:pub(?:\([^)]*\))?[ \t]+)?fn[ \t]+([A-Za-z_][A-Za-z0-9_]*)', re.M)

GENERATED_MARKER = '// ---- Generated by Mage: calls the block function. ----'


class RustSourceError(Exception):
    pass


@dataclass(frozen=True)
class BlockSource:
    code: str
    function: str
    tests: List[str]

    @property
    def lines(self) -> int:
        return self.code.count('\n') + 1


def _blank(match: re.Match) -> str:
    return re.sub(r'[^\n]', ' ', match.group(0))


def function_names(code: str) -> List[str]:
    stripped = _STRINGS.sub(_blank, _COMMENTS.sub(_blank, code))
    return _FUNCTION.findall(stripped)


def analyze(code: str, block_type: BlockType) -> BlockSource:
    expected = FUNCTION_NAMES.get(block_type)
    if expected is None:
        raise RustSourceError(f'Rust blocks cannot be {block_type} blocks.')
    names = function_names(code)
    if 'main' in names:
        raise RustSourceError(
            'A Rust block has no main function: Mage generates it. Remove `fn main` and '
            f'name the block function `{expected}`.',
        )
    if expected not in names:
        found = ', '.join(name for name in names if not name.startswith('test_'))
        raise RustSourceError(
            f'The block has no `{expected}` function. A {block_type.replace("_", " ")} '
            f'block defines `fn {expected}(...)`'
            + (f'; it defines {found}.' if found else '.'),
        )
    tests = [name for name in names if name.startswith('test_')]
    return BlockSource(code=code, function=expected, tests=tests)


def function_line(code: str, name: str) -> Optional[int]:
    """The line of `fn name`, counting from 1."""
    stripped = _STRINGS.sub(_blank, _COMMENTS.sub(_blank, code))
    for match in _FUNCTION.finditer(stripped):
        if match.group(1) == name:
            return stripped.count('\n', 0, match.start(1)) + 1
    return None


MAIN_FILE = 'mage_main.rs'
MAIN_LABEL = '(main generated by Mage)'


def main_rs(source: BlockSource) -> str:
    """The crate's main.rs: the block's code, then the generated main from its own file."""
    code = source.code if source.code.endswith('\n') else source.code + '\n'
    return f'{code}include!("{MAIN_FILE}");\n'


def generated_main(source: BlockSource) -> str:
    tests = ''.join(f'\n        mage::test("{name}", {name}),' for name in source.tests)
    return (
        f'{GENERATED_MARKER}\n'
        'fn main() {\n'
        f'    mage::main({source.function}, vec![{tests}\n    ]);\n'
        '}\n'
    )
